### ISSUE TITLE
Bot for Proxmox LXC container

### ISSUE THREAD

**Issue by fernandeusto** [dgongut/docker-controller-bot#50]
Would it be possible to have docker controller bot for manage the LXC containers of a proxmox server?

**Comment by dgongut** [comment]
Hello, unfortunately I don't know about proxmox at the moment. It is one of my pending tasks.

I also don't know if a bot inside an LXC would see other LXCs, I would say a priori that it is not possible.

What does work because I have users like that is installed inside a VM where docker is installed along with other containers.
